name: Minify on Push
on: push

permissions:
  contents: write

jobs:
  call-minify-workflow:
    uses: Mephisto5558/Mephisto5558/.github/workflows/auto-minify.yml@main
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    with:
      css_input_dir: 'css/*'
      css_output_dir: 'min/css/'
      js_input_dir: 'js/*'
      js_output_dir: 'min/js/'